sources = Client.cpp
libs = -lws2_32
libs_qt = -L C:\msys64\ucrt64\lib -l Qt6Core
includes_qt = -I C:\msys64\ucrt64\include\qt6 -I C:\msys64\ucrt64\include\qt6\QtCore


all:
	g++ $(sources) $(libs) $(libs_qt) $(includes_qt) -g -c -o ../../durakclient.o


